package main

import "fmt"

func main() {
	//SE EJECUTA POR SIEMPRE NO TIENE CONDICION PARA DETERNERSE,USADO DE PREFERENCIA PARA SOCKETS O PARA ACCIONES EN LAS
	//LAS QUE SE ESTE ESPERANDO QUE SE EJECUTE UNA DETERMINADA ACCION
	for {
		fmt.Println("Hola mundo")
	}
}
